import {Tokens} from './Tokens'
import {Monsters} from './Monsters'
import {Extras} from './Extras'
import {getRandomFromObject} from './Helpers'

export const drawMonsterCard = () => {
  return getRandomFromObject(MonsterCards)
}
export const getAmountOfMonsterCards = () => {
  return Object.keys(MonsterCards).length
}

const MonsterCards = {
  Archaic: {
    id: 'Archaic',
    Effects: [Extras.treasure_recoverlostcard],
    players2: [
      {token: Tokens.rubble, frame: 'none'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.stone_golem, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.ancient_artillery, frame: 'normal'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Monsters.ancient_artillery, frame: 'normal'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players3: [
      {token: Tokens.rubble, frame: 'none'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.stone_golem, frame: 'elite'},
      {token: Monsters.stone_golem, frame: 'normal'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Monsters.ancient_artillery, frame: 'normal'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.ancient_artillery, frame: 'normal'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Monsters.ancient_artillery, frame: 'normal'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players4: [
      {token: Tokens.rubble, frame: 'none'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.stone_golem, frame: 'elite'},
      {token: Monsters.stone_golem, frame: 'elite'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Monsters.ancient_artillery, frame: 'normal'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.ancient_artillery, frame: 'normal'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Monsters.ancient_artillery, frame: 'elite'},
      {token: Tokens.treasure, frame: 'none'},
    ],
  },
  // Arid: {id: 'Arid'},
  // Ethereal: {id: 'Ethereal'},
  Corrupted: {
    id: 'Corrupted',
    Effects: [Extras.treasure_recoverlostcard],
    players2: [
      {token: Monsters.cultist, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.night_demon, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.living_bones, frame: 'normal'},
      {token: Monsters.cultist, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players3: [
      {token: Monsters.cultist, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.night_demon, frame: 'elite'},
      {token: Monsters.night_demon, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.living_bones, frame: 'normal'},
      {token: Monsters.cultist, frame: 'normal'},
      {token: Monsters.cultist, frame: 'normal'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players4: [
      {token: Monsters.cultist, frame: 'elite'},
      {token: Monsters.living_bones, frame: 'normal'},
      {token: Monsters.night_demon, frame: 'elite'},
      {token: Monsters.night_demon, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.living_bones, frame: 'elite'},
      {token: Monsters.cultist, frame: 'normal'},
      {token: Monsters.cultist, frame: 'normal'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
  },
  Crushing: {
    id: 'Crushing',
    Effects: [Extras.treasure_5gold],
    players2: [
      {token: Monsters.earth_demon, frame: 'elite'},
      {token: Monsters.wind_demon, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.wind_demon, frame: 'normal'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players3: [
      {token: Monsters.earth_demon, frame: 'elite'},
      {token: Monsters.wind_demon, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.earth_demon, frame: 'normal'},
      {token: Monsters.wind_demon, frame: 'normal'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.wind_demon, frame: 'normal'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players4: [
      {token: Monsters.earth_demon, frame: 'elite'},
      {token: Monsters.wind_demon, frame: 'normal'},
      {token: Monsters.wind_demon, frame: 'normal'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.earth_demon, frame: 'elite'},
      {token: Monsters.wind_demon, frame: 'normal'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.wind_demon, frame: 'normal'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
  },
  Cutthroat: {
    id: 'Cutthroat',
    Effects: [Extras.treasure_5gold, Extras.spike_trap_poison_damage],
    players2: [
      {token: Monsters.bandit_guard, frame: 'elite'},
      {token: Tokens.coin, frame: 'none'},
      {token: Monsters.bandit_archer, frame: 'normal'},
      {token: Monsters.bandit_archer, frame: 'normal'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Monsters.hound, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players3: [
      {token: Monsters.bandit_guard, frame: 'elite'},
      {token: Tokens.coin, frame: 'none'},
      {token: Monsters.bandit_archer, frame: 'elite'},
      {token: Monsters.bandit_archer, frame: 'normal'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Monsters.hound, frame: 'normal'},
      {token: Monsters.bandit_guard, frame: 'normal'},
      {token: Monsters.hound, frame: 'normal'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players4: [
      {token: Monsters.bandit_guard, frame: 'elite'},
      {token: Tokens.coin, frame: 'none'},
      {token: Monsters.bandit_archer, frame: 'elite'},
      {token: Monsters.bandit_archer, frame: 'normal'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Monsters.hound, frame: 'normal'},
      {token: Monsters.bandit_guard, frame: 'normal'},
      {token: Monsters.hound, frame: 'elite'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Monsters.bandit_archer, frame: 'normal'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
  },
  Drowned: {
    id: 'Drowned',
    Effects: [Extras.treasure_recoverlostcard, Extras.spike_trap_stun_damage],
    players2: [
      {token: Monsters.lurker, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.lurker, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.water, frame: 'none'},
      {token: Monsters.living_spirit, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.water, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players3: [
      {token: Monsters.lurker, frame: 'elite'},
      {token: Monsters.lurker, frame: 'normal'},
      {token: Monsters.lurker, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.water, frame: 'none'},
      {token: Monsters.living_spirit, frame: 'normal'},
      {token: Monsters.living_spirit, frame: 'normal'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.water, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players4: [
      {token: Monsters.lurker, frame: 'elite'},
      {token: Monsters.lurker, frame: 'normal'},
      {token: Monsters.lurker, frame: 'normal'},
      {token: Monsters.living_spirit, frame: 'normal'},
      {token: Tokens.water, frame: 'none'},
      {token: Monsters.living_spirit, frame: 'elite'},
      {token: Monsters.living_spirit, frame: 'elite'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.water, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
  },
  Defiled: {
    id: 'Defiled',
    Effects: [
      Extras.treasure_heal5hitpoints,
      Extras.poison_trap_poison_immobilize,
    ],
    players2: [
      {token: Monsters.sun_demon, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.forest_imp, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.forest_imp, frame: 'normal'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Monsters.sun_demon, frame: 'normal'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players3: [
      {token: Monsters.sun_demon, frame: 'elite'},
      {token: Monsters.forest_imp, frame: 'normal'},
      {token: Monsters.forest_imp, frame: 'elite'},
      {token: Monsters.forest_imp, frame: 'normal'},
      {token: Monsters.forest_imp, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.forest_imp, frame: 'normal'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Monsters.sun_demon, frame: 'elite'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players4: [
      {token: Monsters.sun_demon, frame: 'elite'},
      {token: Monsters.forest_imp, frame: 'elite'},
      {token: Monsters.forest_imp, frame: 'elite'},
      {token: Monsters.forest_imp, frame: 'elite'},
      {token: Monsters.forest_imp, frame: 'elite'},
      {token: Monsters.sun_demon, frame: 'normal'},
      {token: Monsters.forest_imp, frame: 'normal'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Monsters.sun_demon, frame: 'elite'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
  },
  Foggy: {
    id: 'Foggy',
    Effects: [Extras.treasure_refresh_2_smallitems],
    players2: [
      {token: Monsters.frost_demon, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.flame_demon, frame: 'elite'},
      {token: Tokens.water, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.water, frame: 'none'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players3: [
      {token: Monsters.frost_demon, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.flame_demon, frame: 'elite'},
      {token: Tokens.water, frame: 'none'},
      {token: Monsters.frost_demon, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Monsters.flame_demon, frame: 'normal'},
      {token: Tokens.water, frame: 'none'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players4: [
      {token: Monsters.frost_demon, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.flame_demon, frame: 'elite'},
      {token: Tokens.water, frame: 'none'},
      {token: Monsters.frost_demon, frame: 'normal'},
      {token: Monsters.flame_demon, frame: 'normal'},
      {token: Monsters.frost_demon, frame: 'normal'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Monsters.flame_demon, frame: 'normal'},
      {token: Tokens.water, frame: 'none'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
  },
  Fortified: {
    id: 'Fortified',
    Effects: [Extras.bear_trap_damage],
    players2: [
      {token: Monsters.city_guard, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Monsters.city_archer, frame: 'normal'},
      {token: Monsters.city_archer, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.bear_trap, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.bear_trap, frame: 'none'},
      {token: Tokens.bear_trap, frame: 'none'},
      {token: Monsters.ancient_artillery, frame: 'normal'},
    ],
    players3: [
      {token: Monsters.city_guard, frame: 'elite'},
      {token: Monsters.city_guard, frame: 'normal'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Monsters.city_archer, frame: 'normal'},
      {token: Monsters.city_archer, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.bear_trap, frame: 'none'},
      {token: Monsters.ancient_artillery, frame: 'normal'},
      {token: Tokens.bear_trap, frame: 'none'},
      {token: Tokens.bear_trap, frame: 'none'},
      {token: Monsters.ancient_artillery, frame: 'normal'},
    ],
    players4: [
      {token: Monsters.city_guard, frame: 'elite'},
      {token: Monsters.city_guard, frame: 'normal'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Monsters.city_archer, frame: 'elite'},
      {token: Monsters.city_archer, frame: 'normal'},
      {token: Monsters.city_archer, frame: 'normal'},
      {token: Tokens.bear_trap, frame: 'none'},
      {token: Monsters.ancient_artillery, frame: 'elite'},
      {token: Tokens.bear_trap, frame: 'none'},
      {token: Tokens.bear_trap, frame: 'none'},
      {token: Monsters.ancient_artillery, frame: 'normal'},
    ],
  },
  Frigid: {
    id: 'Frigid',
    Effects: [Extras.spike_trap_disarm],
    players2: [
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.savaas_icestorm, frame: 'elite'},
      {token: Tokens.water, frame: 'none'},
      {token: Monsters.frost_demon, frame: 'normal'},
      {token: Tokens.water, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
    ],
    players3: [
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.savaas_icestorm, frame: 'elite'},
      {token: Tokens.water, frame: 'none'},
      {token: Monsters.frost_demon, frame: 'normal'},
      {token: Tokens.water, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Monsters.wind_demon, frame: 'normal'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Monsters.wind_demon, frame: 'normal'},
    ],
    players4: [
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.savaas_icestorm, frame: 'elite'},
      {token: Tokens.water, frame: 'none'},
      {token: Monsters.frost_demon, frame: 'elite'},
      {token: Tokens.water, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Monsters.wind_demon, frame: 'elite'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Monsters.wind_demon, frame: 'normal'},
    ],
  },
  Hopeless: {
    id: 'Hopeless',
    Effects: [],
    players2: [
      {token: Monsters.night_demon, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.black_imp, frame: 'normal'},
    ],
    players3: [
      {token: Monsters.night_demon, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.night_demon, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.black_imp, frame: 'elite'},
      {token: Monsters.black_imp, frame: 'elite'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.black_imp, frame: 'normal'},
    ],
    players4: [
      {token: Monsters.night_demon, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.night_demon, frame: 'elite'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.black_imp, frame: 'elite'},
      {token: Monsters.black_imp, frame: 'elite'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.black_imp, frame: 'elite'},
    ],
  },
  Horrific: {
    id: 'Horrific',
    Effects: [Extras.poison_trap_muddle_damage],
    players2: [
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.lurker, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.deep_terror, frame: 'normal'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Monsters.deep_terror, frame: 'elite'},
    ],
    players3: [
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.lurker, frame: 'normal'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.deep_terror, frame: 'elite'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Monsters.deep_terror, frame: 'elite'},
    ],
    players4: [
      {token: Monsters.black_imp, frame: 'elite'},
      {token: Monsters.black_imp, frame: 'elite'},
      {token: Monsters.lurker, frame: 'elite'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.deep_terror, frame: 'elite'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.black_imp, frame: 'elite'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Monsters.deep_terror, frame: 'elite'},
    ],
  },
  Infected: {
    id: 'Infected',
    Effects: [],
    players2: [
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.ooze, frame: 'elite'},
      {token: Monsters.ooze, frame: 'normal'},
      {token: Tokens.coin, frame: 'none'},
    ],
    players3: [
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.ooze, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.ooze, frame: 'elite'},
      {token: Monsters.ooze, frame: 'normal'},
      {token: Tokens.coin, frame: 'none'},
    ],
    players4: [
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Monsters.ooze, frame: 'elite'},
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.ooze, frame: 'elite'},
      {token: Monsters.ooze, frame: 'normal'},
      {token: Tokens.coin, frame: 'none'},
    ],
  },
  Mangy: {
    id: 'Mangy',
    Effects: [Extras.treasure_10gold],
    players2: [
      {token: Monsters.vermling_shaman, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.cave_bear, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.vermling_scout, frame: 'normal'},
      {token: Monsters.vermling_scout, frame: 'normal'},
      {token: Monsters.vermling_scout, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players3: [
      {token: Monsters.vermling_shaman, frame: 'elite'},
      {token: Monsters.vermling_scout, frame: 'normal'},
      {token: Monsters.cave_bear, frame: 'normal'},
      {token: Monsters.vermling_scout, frame: 'normal'},
      {token: Monsters.vermling_scout, frame: 'normal'},
      {token: Monsters.vermling_scout, frame: 'normal'},
      {token: Monsters.vermling_scout, frame: 'elite'},
      {token: Monsters.vermling_scout, frame: 'normal'},
      {token: Monsters.vermling_scout, frame: 'normal'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players4: [
      {token: Monsters.vermling_shaman, frame: 'elite'},
      {token: Monsters.vermling_scout, frame: 'normal'},
      {token: Monsters.cave_bear, frame: 'elite'},
      {token: Monsters.vermling_scout, frame: 'normal'},
      {token: Monsters.vermling_scout, frame: 'normal'},
      {token: Monsters.vermling_scout, frame: 'normal'},
      {token: Monsters.vermling_scout, frame: 'elite'},
      {token: Monsters.vermling_scout, frame: 'elite'},
      {token: Monsters.vermling_scout, frame: 'elite'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
  },
  Putrid: {
    id: 'Putrid',
    Effects: [Extras.treasure_10gold, Extras.poison_trap_muddle_damage],
    players2: [
      {token: Monsters.living_corpse, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.living_corpse, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.ooze, frame: 'normal'},
      {token: Monsters.ooze, frame: 'normal'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players3: [
      {token: Monsters.living_corpse, frame: 'normal'},
      {token: Monsters.living_corpse, frame: 'normal'},
      {token: Monsters.living_corpse, frame: 'elite'},
      {token: Monsters.ooze, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.ooze, frame: 'normal'},
      {token: Monsters.ooze, frame: 'normal'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players4: [
      {token: Monsters.living_corpse, frame: 'normal'},
      {token: Monsters.living_corpse, frame: 'normal'},
      {token: Monsters.living_corpse, frame: 'elite'},
      {token: Monsters.ooze, frame: 'elite'},
      {token: Monsters.living_corpse, frame: 'normal'},
      {token: Monsters.living_corpse, frame: 'normal'},
      {token: Monsters.ooze, frame: 'elite'},
      {token: Monsters.ooze, frame: 'normal'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
  },
  Rotting: {
    id: 'Rotting',
    Effects: [
      Extras.treasure_enemies_suffer_2dmg,
      Extras.poison_trap_stun_poison,
    ],
    players2: [
      {token: Monsters.living_corpse, frame: 'elite'},
      {token: Monsters.living_bones, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.living_bones, frame: 'normal'},
      {token: Monsters.living_spirit, frame: 'elite'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players3: [
      {token: Monsters.living_corpse, frame: 'elite'},
      {token: Monsters.living_bones, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.living_corpse, frame: 'normal'},
      {token: Monsters.living_bones, frame: 'elite'},
      {token: Monsters.living_spirit, frame: 'elite'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Monsters.living_spirit, frame: 'normal'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players4: [
      {token: Monsters.living_corpse, frame: 'elite'},
      {token: Monsters.living_bones, frame: 'normal'},
      {token: Monsters.living_spirit, frame: 'normal'},
      {token: Monsters.living_corpse, frame: 'elite'},
      {token: Monsters.living_bones, frame: 'elite'},
      {token: Monsters.living_spirit, frame: 'elite'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Monsters.living_spirit, frame: 'normal'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.treasure, frame: 'none'},
    ],
  },
  Sealed: {
    id: 'Sealed',
    Effects: [Extras.spike_trap_wound_poison],
    players2: [
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Monsters.rending_drake, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Monsters.spitting_drake, frame: 'normal'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Monsters.spitting_drake, frame: 'normal'},
      {token: Tokens.coin, frame: 'none'},
    ],
    players3: [
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Monsters.rending_drake, frame: 'normal'},
      {token: Monsters.rending_drake, frame: 'normal'},
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Monsters.spitting_drake, frame: 'normal'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Monsters.spitting_drake, frame: 'normal'},
      {token: Tokens.coin, frame: 'none'},
    ],
    players4: [
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Monsters.rending_drake, frame: 'elite'},
      {token: Monsters.rending_drake, frame: 'normal'},
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Monsters.spitting_drake, frame: 'normal'},
      {token: Tokens.thorns, frame: 'none'},
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Monsters.spitting_drake, frame: 'elite'},
      {token: Tokens.coin, frame: 'none'},
    ],
  },
  Tribal: {
    id: 'Tribal',
    Effects: [Extras.spike_trap_wound_disarm],
    players2: [
      {token: Monsters.inox_guard, frame: 'normal'},
      {token: Monsters.inox_guard, frame: 'normal'},
      {token: Monsters.inox_shaman, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.inox_archer, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
    ],
    players3: [
      {token: Monsters.inox_guard, frame: 'normal'},
      {token: Monsters.inox_guard, frame: 'elite'},
      {token: Monsters.inox_shaman, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.inox_archer, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.inox_shaman, frame: 'normal'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
    ],
    players4: [
      {token: Monsters.inox_guard, frame: 'elite'},
      {token: Monsters.inox_guard, frame: 'elite'},
      {token: Monsters.inox_shaman, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.inox_archer, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.inox_shaman, frame: 'normal'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Monsters.inox_archer, frame: 'normal'},
      {token: Tokens.spike_trap, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
    ],
  },
  Unstable: {
    id: 'Unstable',
    Effects: [],
    players2: [
      {token: Monsters.savaas_lavaflow, frame: 'normal'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.earth_demon, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.flame_demon, frame: 'normal'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
    ],
    players3: [
      {token: Monsters.savaas_lavaflow, frame: 'normal'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.earth_demon, frame: 'elite'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.flame_demon, frame: 'normal'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Monsters.flame_demon, frame: 'normal'},
    ],
    players4: [
      {token: Monsters.savaas_lavaflow, frame: 'normal'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.earth_demon, frame: 'elite'},
      {token: Monsters.earth_demon, frame: 'normal'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Tokens.rubble, frame: 'none'},
      {token: Monsters.flame_demon, frame: 'normal'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Tokens.hot_coals, frame: 'none'},
      {token: Monsters.flame_demon, frame: 'elite'},
    ],
  },
  Venomous: {
    id: 'Venomous',
    Effects: [
      Extras.treasure_poison_all_enemies,
      Extras.poison_trap_stun_poison,
    ],
    players2: [
      {token: Monsters.harrower_infester, frame: 'elite'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players3: [
      {token: Monsters.harrower_infester, frame: 'elite'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.harrower_infester, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.black_imp, frame: 'elite'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players4: [
      {token: Monsters.harrower_infester, frame: 'elite'},
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.giant_viper, frame: 'elite'},
      {token: Monsters.giant_viper, frame: 'normal'},
      {token: Monsters.harrower_infester, frame: 'elite'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Tokens.poison_trap, frame: 'none'},
      {token: Monsters.black_imp, frame: 'normal'},
      {token: Monsters.black_imp, frame: 'elite'},
      {token: Tokens.treasure, frame: 'none'},
    ],
  },
  Wild: {
    id: 'Wild',
    Effects: [
      Extras.bear_trap_damage_immobilize,
      Extras.treasure_cureallnegcond,
    ],
    players2: [
      {token: Monsters.cave_bear, frame: 'normal'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Monsters.hound, frame: 'normal'},
      {token: Monsters.hound, frame: 'normal'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.forest_imp, frame: 'elite'},
      {token: Tokens.bear_trap, frame: 'none'},
      {token: Tokens.bear_trap, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.forest_imp, frame: 'normal'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players3: [
      {token: Monsters.cave_bear, frame: 'elite'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Monsters.hound, frame: 'normal'},
      {token: Monsters.hound, frame: 'normal'},
      {token: Monsters.forest_imp, frame: 'normal'},
      {token: Monsters.forest_imp, frame: 'elite'},
      {token: Tokens.bear_trap, frame: 'none'},
      {token: Tokens.bear_trap, frame: 'none'},
      {token: Tokens.empty, frame: 'none'},
      {token: Monsters.forest_imp, frame: 'normal'},
      {token: Tokens.treasure, frame: 'none'},
    ],
    players4: [
      {token: Monsters.cave_bear, frame: 'elite'},
      {token: Tokens.coin, frame: 'none'},
      {token: Tokens.coin, frame: 'none'},
      {token: Monsters.hound, frame: 'elite'},
      {token: Monsters.hound, frame: 'normal'},
      {token: Monsters.forest_imp, frame: 'normal'},
      {token: Monsters.forest_imp, frame: 'elite'},
      {token: Tokens.bear_trap, frame: 'none'},
      {token: Tokens.bear_trap, frame: 'none'},
      {token: Monsters.cave_bear, frame: 'normal'},
      {token: Monsters.forest_imp, frame: 'normal'},
      {token: Tokens.treasure, frame: 'none'},
    ],
  },
}
