import {monsterPath} from '../config'
const fileFormat = '.webp'
const drawCoords = {x: 0, y: 0}
const aspectRatio = 4.4
export const Monsters = {
  rending_drake: {
    id: 'rending_drake',
    location: `${monsterPath}rending_drake${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  cave_bear: {
    id: 'cave_bear',
    location: `${monsterPath}cave_bear${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  forest_imp: {
    id: 'forest_imp',
    location: `${monsterPath}forest_imp${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  hound: {
    id: 'hound',
    location: `${monsterPath}hound${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  cultist: {
    id: 'cultist',
    location: `${monsterPath}cultist${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  night_demon: {
    id: 'night_demon',
    location: `${monsterPath}night_demon${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  living_bones: {
    id: 'living_bones',
    location: `${monsterPath}living_bones${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  stone_golem: {
    id: 'stone_golem',
    location: `${monsterPath}stone_golem${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  ancient_artillery: {
    id: 'ancient_artillery',
    location: `${monsterPath}ancient_artillery${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  wind_demon: {
    id: 'wind_demon',
    location: `${monsterPath}wind_demon${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  earth_demon: {
    id: 'earth_demon',
    location: `${monsterPath}earth_demon${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  bandit_guard: {
    id: 'bandit_guard',
    location: `${monsterPath}bandit_guard${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  bandit_archer: {
    id: 'bandit_archer',
    location: `${monsterPath}bandit_archer${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  lurker: {
    id: 'lurker',
    location: `${monsterPath}lurker${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  living_spirit: {
    id: 'living_spirit',
    location: `${monsterPath}living_spirit${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  sun_demon: {
    id: 'sun_demon',
    location: `${monsterPath}sun_demon${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  frost_demon: {
    id: 'frost_demon',
    location: `${monsterPath}frost_demon${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  flame_demon: {
    id: 'flame_demon',
    location: `${monsterPath}flame_demon${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  city_archer: {
    id: 'city_archer',
    location: `${monsterPath}city_archer${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  city_guard: {
    id: 'city_guard',
    location: `${monsterPath}city_guard${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  savaas_icestorm: {
    id: 'savaas_icestorm',
    location: `${monsterPath}savaas_icestorm${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  black_imp: {
    id: 'black_imp',
    location: `${monsterPath}black_imp${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  deep_terror: {
    id: 'deep_terror',
    location: `${monsterPath}deep_terror${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  giant_viper: {
    id: 'giant_viper',
    location: `${monsterPath}giant_viper${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  ooze: {
    id: 'ooze',
    location: `${monsterPath}ooze${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  vermling_scout: {
    id: 'vermling_scout',
    location: `${monsterPath}vermling_scout${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  vermling_shaman: {
    id: 'vermling_shaman',
    location: `${monsterPath}vermling_shaman${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  inox_shaman: {
    id: 'inox_shaman',
    location: `${monsterPath}inox_shaman${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  inox_archer: {
    id: 'inox_archer',
    location: `${monsterPath}inox_archer${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  inox_guard: {
    id: 'inox_guard',
    location: `${monsterPath}inox_guard${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  spitting_drake: {
    id: 'spitting_drake',
    location: `${monsterPath}spitting_drake${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  savaas_lavaflow: {
    id: 'savaas_lavaflow',
    location: `${monsterPath}savaas_lavaflow${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  living_corpse: {
    id: 'living_corpse',
    location: `${monsterPath}living_corpse${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  inox_bodyguard: {
    id: 'inox_bodyguard',
    location: `${monsterPath}inox_bodyguard${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
  harrower_infester: {
    id: 'harrower_infester',
    location: `${monsterPath}harrower_infester${fileFormat}`,
    aspectRatio,
    drawCoords,
    itemType: 'monster',
  },
}
