import {Tokens} from './Tokens'
import {EmptySlots} from './EmptySlots'
import {Tiles} from './Tiles'
import {getRandomFromObject} from './Helpers'

export const drawScenarioCard = () => {
  return getRandomFromObject(ScenarioCards)
}

export const ScenarioCards = {
  Alcove: {
    id: 'Alcove',
    Tiles: [
      {
        Map: Tiles.J2a,
        staticRender: [
          {token: EmptySlots.slot1, cubeCoord: {r: 1, g: 1, b: -2}},
          {token: EmptySlots.slot2, cubeCoord: {r: -2, g: 2, b: 0}},
          {token: EmptySlots.slot3, cubeCoord: {r: -2, g: 3, b: -1}},
          {token: EmptySlots.slot4, cubeCoord: {r: -3, g: 4, b: -1}},
          {token: EmptySlots.slot5, cubeCoord: {r: -4, g: 5, b: -1}},
          {token: EmptySlots.slot6, cubeCoord: {r: 2, g: 0, b: -2}},
          {token: EmptySlots.slot7, cubeCoord: {r: 2, g: 1, b: -3}},
          {token: EmptySlots.slot8, cubeCoord: {r: 3, g: 0, b: -3}},
          {token: EmptySlots.slot9, cubeCoord: {r: 2, g: 2, b: -4}},
          {token: EmptySlots.slot10, cubeCoord: {r: -4, g: 4, b: 0}},
          {token: EmptySlots.slot11, cubeCoord: {r: -5, g: 5, b: 0}},
          {token: EmptySlots.slot12, cubeCoord: {r: -4, g: 3, b: 1}},
          {token: Tokens.boulder_1, cubeCoord: {r: 1, g: 2, b: -3}},
          {token: Tokens.boulder_1, cubeCoord: {r: -3, g: 3, b: 0}},
          {token: Tokens.boulder_1, cubeCoord: {r: -3, g: 2, b: 1}},
          {token: Tokens.entrance_left_b, cubeCoord: {r: -1, g: 0, b: 1}},
          {token: Tokens.exit_right_b, cubeCoord: {r: 4, g: 1, b: -5}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['B'],
    exits: ['B'],
    minor: 'All enemies gain SHIELD[1] this round.',
    major: 'All enemies gain SHIELD[1] permanently.',
  },
  Altar: {
    id: 'Altar',
    Tiles: [
      {
        Map: Tiles.L2b,
        staticRender: [
          {token: EmptySlots.slot1, cubeCoord: {r: -2, g: 4, b: -2}},
          {token: EmptySlots.slot2, cubeCoord: {r: -1, g: 3, b: -2}},
          {token: EmptySlots.slot3, cubeCoord: {r: -1, g: 2, b: -1}},
          {token: EmptySlots.slot4, cubeCoord: {r: 2, g: 1, b: -3}},
          {token: EmptySlots.slot5, cubeCoord: {r: 3, g: 1, b: -4}},
          {token: EmptySlots.slot6, cubeCoord: {r: 2, g: 2, b: -4}},
          {token: EmptySlots.slot7, cubeCoord: {r: 1, g: 6, b: -7}},
          {token: EmptySlots.slot8, cubeCoord: {r: 1, g: 5, b: -6}},
          {token: EmptySlots.slot9, cubeCoord: {r: 1, g: 4, b: -5}},
          {token: EmptySlots.slot10, cubeCoord: {r: 2, g: 0, b: -2}},
          {token: EmptySlots.slot11, cubeCoord: {r: 1, g: 0, b: -1}},
          {token: EmptySlots.slot12, cubeCoord: {r: 0, g: 0, b: 0}},
          {token: Tokens.altar, cubeCoord: {r: 1, g: 2, b: -3}},
          {token: Tokens.altar, cubeCoord: {r: 0, g: 4, b: -4}},
          {token: Tokens.stone_pillar, cubeCoord: {r: 0, g: 3, b: -3}},
          {token: Tokens.stone_pillar, cubeCoord: {r: 1, g: 3, b: -4}},
          {token: Tokens.entrance_right_b, cubeCoord: {r: 3, g: 3, b: -6}},
          {token: Tokens.exit_left_b, cubeCoord: {r: -2, g: 3, b: -1}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['B'],
    exits: ['B'],
    minor: 'Add 3 BLESS cards to the monster attack modifier deck.',
    major: 'Add 7 BLESS cards to the monster attack modifier deck.',
  },
  Armory: {
    id: 'Armory',
    Tiles: [
      {
        Map: Tiles.B2b,
        staticRender: [
          {
            token: Tokens.corridor_2_s,
            cubeCoord: {r: 2.5, g: 2, b: -2.5},
          },
          {
            token: Tokens.shelf_2,
            cubeCoord: {r: 0.5, g: 0, b: -0.5},
          },
          {
            token: Tokens.shelf_2,
            cubeCoord: {r: -0.5, g: 2, b: -2.5},
          },
          {token: EmptySlots.slot2, cubeCoord: {r: 2, g: 2, b: -4}},
          {token: EmptySlots.slot3, cubeCoord: {r: 3, g: 0, b: -3}},
          {token: EmptySlots.slot7, cubeCoord: {r: 1, g: 2, b: -3}},
          {token: EmptySlots.slot8, cubeCoord: {r: 2, g: 1, b: -3}},
          {token: EmptySlots.slot9, cubeCoord: {r: 1, g: 1, b: -2}},
          {token: EmptySlots.slot10, cubeCoord: {r: 1, g: 3, b: -4}},
          {token: EmptySlots.slot11, cubeCoord: {r: 0, g: 3, b: -3}},
          {token: EmptySlots.slot12, cubeCoord: {r: -1, g: 3, b: -2}},

          {token: Tokens.exit_left_b, cubeCoord: {r: -1, g: 1, b: 0}},
        ],
        offset: {x: 0, y: 0},
      },
      {
        Map: Tiles.A3b,
        staticRender: [
          {token: Tokens.corridor_1_s, cubeCoord: {r: -1, g: 0, b: 1}},
          {token: EmptySlots.slot1, cubeCoord: {r: -1, g: 0, b: 1}},
          {token: EmptySlots.slot4, cubeCoord: {r: 0, g: 1, b: -1}},
          {token: EmptySlots.slot5, cubeCoord: {r: 1, g: 0, b: -1}},
          {token: EmptySlots.slot6, cubeCoord: {r: 0, g: 0, b: 0}},
          {token: Tokens.entrance_right_b, cubeCoord: {r: 4, g: 0, b: -4}},
          {
            token: Tokens.entrance_right_a,
            cubeCoord: {r: 3, g: -1, b: -2},
          },
        ],
        offset: {x: 420, y: 90},
      },
    ],
    entries: ['A', 'B'],
    exits: ['B'],
    minor: 'POISON all characters.',
    major: 'All enemies add +1 ATTACK to all of their attacks.',
  },
  Burrow: {
    id: 'Burrow',
    Tiles: [
      {
        Map: Tiles.A1a,
        staticRender: [
          {
            token: Tokens.corridor_2_s,
            cubeCoord: {r: 3.5, g: 1, b: -3.5},
          },
          {token: EmptySlots.slot3, cubeCoord: {r: 3, g: 1, b: -4}},
          {token: EmptySlots.slot4, cubeCoord: {r: 3, g: 0, b: -3}},
          {token: EmptySlots.slot8, cubeCoord: {r: 1, g: 1, b: -2}},
          {token: EmptySlots.slot9, cubeCoord: {r: 2, g: 0, b: -2}},
          {token: Tokens.entrance_left_b, cubeCoord: {r: -1, g: 0, b: 1}},
        ],
        offset: {x: 0, y: 0},
      },
      {
        Map: Tiles.A2a,
        staticRender: [
          {token: Tokens.corridor_1_s, cubeCoord: {r: -1, g: 0, b: 1}},
          {token: Tokens.boulder_1, cubeCoord: {r: 2, g: 0, b: -2}},
          {token: EmptySlots.slot1, cubeCoord: {r: -1, g: 1, b: 0}},
          {token: EmptySlots.slot2, cubeCoord: {r: -1, g: 0, b: 1}},
          {token: EmptySlots.slot5, cubeCoord: {r: 0, g: 1, b: -1}},
          {token: EmptySlots.slot6, cubeCoord: {r: 1, g: 0, b: -1}},
          {token: EmptySlots.slot7, cubeCoord: {r: 1, g: 1, b: -2}},
          {token: EmptySlots.slot10, cubeCoord: {r: 2, g: 1, b: -3}},
          {token: EmptySlots.slot11, cubeCoord: {r: 3, g: 0, b: -3}},
          {token: EmptySlots.slot12, cubeCoord: {r: 3, g: 1, b: -4}},
          {token: Tokens.exit_right_b, cubeCoord: {r: 4, g: 0, b: -4}},
        ],
        offset: {x: 520, y: 0},
      },
    ],
    entries: ['B'],
    exits: ['B'],
    minor: 'STUN the character who opened the door.',
    major: 'MUDDLE, POISON and WOUND all characters.',
  },
  Cabin: {
    id: 'Cabin',
    Tiles: [
      {
        Map: Tiles.I2b,
        staticRender: [
          {token: EmptySlots.slot1, cubeCoord: {r: 3, g: 2, b: -5}},
          {token: EmptySlots.slot2, cubeCoord: {r: 4, g: 0, b: -4}},
          {token: EmptySlots.slot3, cubeCoord: {r: 5, g: 0, b: -5}},
          {token: EmptySlots.slot4, cubeCoord: {r: 0, g: 4, b: -4}},
          {token: EmptySlots.slot5, cubeCoord: {r: 1, g: 4, b: -5}},
          {token: EmptySlots.slot6, cubeCoord: {r: 1, g: 2, b: -3}},
          {token: EmptySlots.slot7, cubeCoord: {r: 2, g: 1, b: -3}},
          {token: EmptySlots.slot8, cubeCoord: {r: 1, g: 1, b: -2}},
          {token: EmptySlots.slot9, cubeCoord: {r: 0, g: 1, b: -1}},
          {token: EmptySlots.slot10, cubeCoord: {r: 2, g: 4, b: -6}},
          {token: EmptySlots.slot11, cubeCoord: {r: 3, g: 3, b: -6}},
          {token: EmptySlots.slot12, cubeCoord: {r: 3, g: 4, b: -7}},
          {token: Tokens.table_2, cubeCoord: {r: 0.5, g: 3, b: -3.5}},
          {token: Tokens.barrel, cubeCoord: {r: 4, g: 1, b: -5}},
          {token: Tokens.cabinet, cubeCoord: {r: 0, g: 2, b: -2}},
          {token: Tokens.cabinet, cubeCoord: {r: 4, g: 2, b: -6}},
          {token: Tokens.entrance_left_a, cubeCoord: {r: 3, g: -1, b: -2}},
          {token: Tokens.exit_right_a, cubeCoord: {r: 0, g: 5, b: -5}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['A'],
    exits: ['A'],
    minor: 'The character who opened the door loses a card.',
    major: 'The character who opened the door loses 2 cards.',
  },
  Cave: {
    id: 'Cave',
    Tiles: [
      {
        Map: Tiles.E1b,
        staticRender: [
          {token: EmptySlots.slot1, cubeCoord: {r: 0, g: 1, b: -1}},
          {token: EmptySlots.slot2, cubeCoord: {r: 2, g: 3, b: -5}},
          {token: EmptySlots.slot3, cubeCoord: {r: -1, g: 3, b: -2}},
          {token: EmptySlots.slot4, cubeCoord: {r: -1, g: 1, b: 0}},
          {token: EmptySlots.slot5, cubeCoord: {r: 2, g: 2, b: -4}},
          {token: EmptySlots.slot6, cubeCoord: {r: 2, g: 1, b: -3}},
          {token: EmptySlots.slot7, cubeCoord: {r: 0, g: 3, b: -3}},
          {token: EmptySlots.slot8, cubeCoord: {r: 1, g: 1, b: -2}},
          {token: EmptySlots.slot9, cubeCoord: {r: 1, g: 0, b: -1}},
          {token: EmptySlots.slot10, cubeCoord: {r: 3, g: 0, b: -3}},
          {token: EmptySlots.slot11, cubeCoord: {r: 0, g: 0, b: 0}},
          {token: EmptySlots.slot12, cubeCoord: {r: 1, g: 4, b: -5}},
          {token: Tokens.rock_column, cubeCoord: {r: 2, g: 0, b: -2}},
          {token: Tokens.rock_column, cubeCoord: {r: -1, g: 2, b: -1}},
          {token: Tokens.rock_column, cubeCoord: {r: 1, g: 3, b: -4}},
          {
            token: Tokens.entrance_left_a,
            cubeCoord: {r: -2, g: 5, b: -3},
          },
          {token: Tokens.exit_right_b, cubeCoord: {r: 3, g: 2, b: -5}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['A'],
    exits: ['B'],
    minor: 'The character who opened the door suffers 6 damage.',
    major: 'The character who opened the door suffers 6 damage and gains STUN.',
  },
  Clearing: {
    id: 'Clearing',
    Tiles: [
      {
        Map: Tiles.L3a,
        staticRender: [
          {token: EmptySlots.slot1, cubeCoord: {r: 2, g: 0, b: -2}},
          {token: EmptySlots.slot2, cubeCoord: {r: 3, g: 0, b: -3}},
          {token: EmptySlots.slot3, cubeCoord: {r: 1, g: 2, b: -3}},
          {token: EmptySlots.slot4, cubeCoord: {r: -1, g: 6, b: -5}},
          {token: EmptySlots.slot5, cubeCoord: {r: 0, g: 6, b: -6}},
          {token: EmptySlots.slot6, cubeCoord: {r: 0, g: 4, b: -4}},
          {token: EmptySlots.slot7, cubeCoord: {r: -1, g: 2, b: -1}},
          {token: EmptySlots.slot8, cubeCoord: {r: 0, g: 1, b: -1}},
          {token: EmptySlots.slot9, cubeCoord: {r: 1, g: 0, b: -1}},
          {token: EmptySlots.slot10, cubeCoord: {r: -2, g: 4, b: -2}},
          {token: EmptySlots.slot11, cubeCoord: {r: -2, g: 5, b: -3}},
          {token: EmptySlots.slot12, cubeCoord: {r: -2, g: 6, b: -4}},
          {
            token: Tokens.entrance_right_b,
            cubeCoord: {r: 3, g: 3, b: -6},
          },

          {token: Tokens.exit_left_b, cubeCoord: {r: -2, g: 3, b: -1}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['B'],
    exits: ['B'],
    minor: 'All elements become inert.',
    major: 'Characters can no longer consume elements.',
  },
  Corridor: {
    id: 'Corridor',
    Tiles: [
      {
        Map: Tiles.F1a,
        staticRender: [
          {token: Tokens.altar, cubeCoord: {r: 1, g: 2, b: -3}},
          {token: Tokens.altar, cubeCoord: {r: -1, g: 6, b: -5}},
          {token: Tokens.altar, cubeCoord: {r: -2, g: 4, b: -2}},
          {token: EmptySlots.slot1, cubeCoord: {r: 0, g: 3, b: -3}},
          {token: EmptySlots.slot2, cubeCoord: {r: -1, g: 3, b: -2}},
          {token: EmptySlots.slot3, cubeCoord: {r: -1, g: 5, b: -4}},
          {token: EmptySlots.slot4, cubeCoord: {r: -2, g: 5, b: -3}},
          {token: EmptySlots.slot5, cubeCoord: {r: -2, g: 6, b: -4}},
          {token: EmptySlots.slot6, cubeCoord: {r: -3, g: 6, b: -3}},
          {token: EmptySlots.slot7, cubeCoord: {r: 0, g: 2, b: -2}},
          {token: EmptySlots.slot8, cubeCoord: {r: -1, g: 2, b: -1}},
          {token: EmptySlots.slot9, cubeCoord: {r: 0, g: 1, b: -1}},
          {token: EmptySlots.slot10, cubeCoord: {r: 1, g: 1, b: -2}},
          {token: EmptySlots.slot11, cubeCoord: {r: 1, g: 0, b: -1}},
          {token: EmptySlots.slot12, cubeCoord: {r: 2, g: 0, b: -2}},
          {
            token: Tokens.entrance_left_a,
            cubeCoord: {r: -3, g: 9, b: -6},
          },
          {token: Tokens.exit_left_b, cubeCoord: {r: -1, g: 1, b: 0}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['A'],
    exits: ['B'],
    minor: 'IMMOBILIZE all characters.',
    major: 'STUN all characters.',
  },
  Crossroads: {
    id: 'Crossroads',
    Tiles: [
      {
        Map: Tiles.H2b,
        staticRender: [
          {token: Tokens.totem, cubeCoord: {r: 2, g: 2, b: -4}},
          {token: EmptySlots.slot1, cubeCoord: {r: 0, g: 5, b: -5}},
          {token: EmptySlots.slot2, cubeCoord: {r: -1, g: 6, b: -5}},
          {token: EmptySlots.slot3, cubeCoord: {r: 1, g: 2, b: -3}},
          {token: EmptySlots.slot4, cubeCoord: {r: 1, g: 1, b: -2}},
          {token: EmptySlots.slot5, cubeCoord: {r: 2, g: 1, b: -3}},
          {token: EmptySlots.slot6, cubeCoord: {r: 5, g: 1, b: -6}},
          {token: EmptySlots.slot7, cubeCoord: {r: 5, g: 0, b: -5}},
          {token: EmptySlots.slot8, cubeCoord: {r: 4, g: 1, b: -5}},
          {token: EmptySlots.slot9, cubeCoord: {r: 3, g: 0, b: -3}},
          {token: EmptySlots.slot10, cubeCoord: {r: 1, g: 4, b: -5}},
          {token: EmptySlots.slot11, cubeCoord: {r: 1, g: 5, b: -6}},
          {token: EmptySlots.slot12, cubeCoord: {r: 0, g: 6, b: -6}},

          {
            token: Tokens.entrance_left_b,
            cubeCoord: {r: -1, g: 0, b: 1},
          },

          {token: Tokens.exit_right_b, cubeCoord: {r: 6, g: 0, b: -6}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['B'],
    exits: ['B'],
    minor: 'All characters discard 2 cards.',
    major: 'All characters lose a card.',
  },
  DeadEnd: {
    id: 'DeadEnd',
    Tiles: [
      {
        Map: Tiles.K1b,
        staticRender: [
          {token: Tokens.stalagmites, cubeCoord: {r: -3, g: 3, b: 0}},
          {token: Tokens.stalagmites, cubeCoord: {r: -1, g: 3, b: -2}},
          {token: Tokens.rock_column, cubeCoord: {r: -1, g: 2, b: -1}},
          {token: EmptySlots.slot1, cubeCoord: {r: 2, g: 3, b: -5}},
          {token: EmptySlots.slot2, cubeCoord: {r: 3, g: 2, b: -5}},
          {token: EmptySlots.slot3, cubeCoord: {r: 1, g: 3, b: -4}},
          {token: EmptySlots.slot4, cubeCoord: {r: 2, g: 5, b: -7}},
          {token: EmptySlots.slot5, cubeCoord: {r: 3, g: 4, b: -7}},
          {token: EmptySlots.slot6, cubeCoord: {r: 1, g: 5, b: -6}},
          {token: EmptySlots.slot7, cubeCoord: {r: 0, g: 1, b: -1}},
          {token: EmptySlots.slot8, cubeCoord: {r: 0, g: 0, b: 0}},
          {token: EmptySlots.slot9, cubeCoord: {r: -1, g: 1, b: 0}},
          {token: EmptySlots.slot10, cubeCoord: {r: -3, g: 4, b: -1}},
          {token: EmptySlots.slot11, cubeCoord: {r: -3, g: 5, b: -2}},
          {token: EmptySlots.slot12, cubeCoord: {r: -4, g: 5, b: -1}},

          {
            token: Tokens.entrance_left_a,
            cubeCoord: {r: 2, g: -1, b: -1},
          },
          {token: Tokens.exit_right_a, cubeCoord: {r: 3, g: 5, b: -8}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['A'],
    exits: ['A'],
    minor: 'All characters suffer 3 damage.',
    major: 'All characters suffer 7 damage.',
  },
  Den: {
    id: 'Den',
    Tiles: [
      {
        Map: Tiles.D2b,
        staticRender: [
          {token: Tokens.nest, cubeCoord: {r: 0, g: 3, b: -3}},
          {token: EmptySlots.slot1, cubeCoord: {r: 1, g: 3, b: -4}},
          {token: EmptySlots.slot2, cubeCoord: {r: 1, g: 0, b: -1}},
          {token: EmptySlots.slot3, cubeCoord: {r: 2, g: 0, b: -2}},
          {token: EmptySlots.slot4, cubeCoord: {r: -1, g: 4, b: -3}},
          {token: EmptySlots.slot5, cubeCoord: {r: 0, g: 4, b: -4}},
          {token: EmptySlots.slot6, cubeCoord: {r: 0, g: 2, b: -2}},
          {token: EmptySlots.slot7, cubeCoord: {r: -1, g: 2, b: -1}},
          {token: EmptySlots.slot8, cubeCoord: {r: -2, g: 3, b: -1}},
          {token: EmptySlots.slot9, cubeCoord: {r: 1, g: 1, b: -2}},
          {token: EmptySlots.slot10, cubeCoord: {r: 1, g: 2, b: -3}},
          {token: EmptySlots.slot11, cubeCoord: {r: 2, g: 1, b: -3}},
          {token: EmptySlots.slot12, cubeCoord: {r: 2, g: 2, b: -4}},

          {
            token: Tokens.entrance_left_a,
            cubeCoord: {r: -2, g: 1, b: 1},
          },
          {token: Tokens.exit_right_a, cubeCoord: {r: -2, g: 5, b: -3}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['A'],
    exits: ['A'],
    minor: 'All enemies gain "Retaliate 2, Range 3" this round.',
    major: 'All enemies gain "Retaliate 2, Range 3" permanently.',
  },
  Encampment: {
    id: 'Encampment',
    Tiles: [
      {
        Map: Tiles.M1b,
        staticRender: [
          {
            token: Tokens.skew_log_2,
            cubeCoord: {r: -0.5, g: 1.5, b: -1},
          },
          {token: Tokens.skew_log_2, cubeCoord: {r: 0.5, g: 4.5, b: -5}},
          {token: EmptySlots.slot1, cubeCoord: {r: 0, g: 4, b: -4}},
          {token: EmptySlots.slot2, cubeCoord: {r: 1, g: 3, b: -4}},
          {token: EmptySlots.slot3, cubeCoord: {r: 1, g: 2, b: -3}},
          {token: EmptySlots.slot4, cubeCoord: {r: -1, g: 4, b: -3}},
          {token: EmptySlots.slot5, cubeCoord: {r: -1, g: 3, b: -2}},
          {token: EmptySlots.slot6, cubeCoord: {r: 0, g: 2, b: -2}},
          {token: EmptySlots.slot7, cubeCoord: {r: -1, g: 1, b: 0}},
          {token: EmptySlots.slot8, cubeCoord: {r: 2, g: 1, b: -3}},
          {token: EmptySlots.slot9, cubeCoord: {r: -2, g: 5, b: -3}},
          {token: EmptySlots.slot10, cubeCoord: {r: 0, g: 6, b: -6}},
          {token: EmptySlots.slot11, cubeCoord: {r: 2, g: 4, b: -6}},
          {token: EmptySlots.slot12, cubeCoord: {r: 1, g: 5, b: -6}},
          {token: Tokens.nest, cubeCoord: {r: 0, g: 3, b: -3}},

          {
            token: Tokens.entrance_left_b,
            cubeCoord: {r: -3, g: 3, b: 0},
          },
          {token: Tokens.exit_right_a, cubeCoord: {r: 4, g: 0, b: -4}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['B'],
    exits: ['A'],
    minor: 'Upgrade a normal enemy in this room to elite.',
    major: 'Replace an elite enemy in the previous room.',
  },
  Hallway: {
    id: 'Hallway',
    Tiles: [
      {
        Map: Tiles.G2b,
        staticRender: [
          {token: EmptySlots.slot1, cubeCoord: {r: 2, g: 1, b: -3}},
          {token: EmptySlots.slot2, cubeCoord: {r: 3, g: 0, b: -3}},
          {token: EmptySlots.slot3, cubeCoord: {r: 1, g: 2, b: -3}},
          {token: EmptySlots.slot4, cubeCoord: {r: 3, g: 1, b: -4}},
          {token: EmptySlots.slot5, cubeCoord: {r: 4, g: 0, b: -4}},
          {token: EmptySlots.slot6, cubeCoord: {r: 2, g: 2, b: -4}},
          {token: EmptySlots.slot7, cubeCoord: {r: 5, g: 0, b: -5}},
          {token: EmptySlots.slot8, cubeCoord: {r: 6, g: 0, b: -6}},
          {token: EmptySlots.slot9, cubeCoord: {r: 5, g: 1, b: -6}},
          {token: EmptySlots.slot10, cubeCoord: {r: 4, g: 2, b: -6}},
          {token: EmptySlots.slot11, cubeCoord: {r: 5, g: 2, b: -7}},
          {token: EmptySlots.slot12, cubeCoord: {r: 6, g: 2, b: -8}},
          {
            token: Tokens.entrance_left_b,
            cubeCoord: {r: -1, g: 1, b: 0},
          },
          {
            token: Tokens.entrance_left_a,
            cubeCoord: {r: -1, g: 3, b: -2},
          },
          {token: Tokens.exit_right_b, cubeCoord: {r: 7, g: 1, b: -8}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['A', 'B'],
    exits: ['B'],
    minor: 'All characters consume 1 small item.',
    major: 'All characters consume and spend all items.',
  },
  Hovel: {
    id: 'Hovel',
    Tiles: [
      {
        Map: Tiles.B2a,
        staticRender: [
          {
            token: Tokens.corridor_2_w,
            cubeCoord: {r: -0.5, g: 4, b: -3.5},
          },
          {token: Tokens.table_2, cubeCoord: {r: 1.5, g: 2, b: -3.5}},
          {token: EmptySlots.slot3, cubeCoord: {r: 1, g: 3, b: -4}},
          {token: EmptySlots.slot4, cubeCoord: {r: 0, g: 3, b: -3}},
          {token: EmptySlots.slot5, cubeCoord: {r: 2, g: 1, b: -3}},
          {token: EmptySlots.slot6, cubeCoord: {r: -1, g: 4, b: -3}},
          {token: EmptySlots.slot7, cubeCoord: {r: 0, g: 4, b: -4}},
          {token: EmptySlots.slot11, cubeCoord: {r: 3, g: 0, b: -3}},
          {token: Tokens.entrance_left_b, cubeCoord: {r: -1, g: 1, b: 0}},
          {token: Tokens.entrance_left_a, cubeCoord: {r: 2, g: -1, b: -1}},
        ],
        offset: {x: 0, y: -60},
      },
      {
        Map: Tiles.C1b_rotated,
        staticRender: [
          {token: Tokens.crate, cubeCoord: {r: 0, g: 2, b: -2}},
          {token: EmptySlots.slot1, cubeCoord: {r: 1, g: 1, b: -2}},
          {token: EmptySlots.slot2, cubeCoord: {r: 0, g: 1, b: -1}},
          {token: EmptySlots.slot8, cubeCoord: {r: 2, g: 1, b: -3}},
          {token: EmptySlots.slot9, cubeCoord: {r: -1, g: 1, b: 0}},
          {token: EmptySlots.slot10, cubeCoord: {r: 1, g: 2, b: -3}},
          {token: EmptySlots.slot12, cubeCoord: {r: -1, g: 2, b: -1}},
          {token: Tokens.exit_right_a, cubeCoord: {r: 2, g: 2, b: -4}},
        ],
        offset: {x: 6, y: 373},
      },
    ],
    entries: ['A', 'B'],
    exits: ['A'],
    minor: 'WOUND all characters.',
    major: 'WOUND all characters permanently.',
  },
  Library: {
    id: 'Library',
    Tiles: [
      {
        Map: Tiles.M1a,
        staticRender: [
          {
            token: Tokens.skew_bookcase_2,
            cubeCoord: {r: 2, g: 3.5, b: -5.5},
          },
          {
            token: Tokens.skew_bookcase_2,
            cubeCoord: {r: -1, g: 5.5, b: -4.5},
          },
          {
            token: Tokens.skew_bookcase_2,
            cubeCoord: {r: -3, g: 4.5, b: -2.5},
          },
          {
            token: Tokens.skew_bookcase_2,
            cubeCoord: {r: 0, g: 0.5, b: -0.5},
          },
          {
            token: Tokens.stone_pillar,
            cubeCoord: {r: 0, g: 2, b: -2},
          },
          {
            token: Tokens.stone_pillar,
            cubeCoord: {r: -1, g: 4, b: -3},
          },
          {token: EmptySlots.slot1, cubeCoord: {r: 0, g: 4, b: -4}},
          {token: EmptySlots.slot2, cubeCoord: {r: 0, g: 3, b: -3}},
          {token: EmptySlots.slot3, cubeCoord: {r: 1, g: 4, b: -5}},
          {token: EmptySlots.slot4, cubeCoord: {r: -2, g: 4, b: -2}},
          {token: EmptySlots.slot5, cubeCoord: {r: -2, g: 5, b: -3}},
          {token: EmptySlots.slot6, cubeCoord: {r: -2, g: 6, b: -4}},
          {token: EmptySlots.slot7, cubeCoord: {r: 1, g: 2, b: -3}},
          {token: EmptySlots.slot8, cubeCoord: {r: 2, g: 1, b: -3}},
          {token: EmptySlots.slot9, cubeCoord: {r: 1, g: 1, b: -2}},
          {token: EmptySlots.slot10, cubeCoord: {r: 0, g: 5, b: -5}},
          {token: EmptySlots.slot11, cubeCoord: {r: 1, g: 5, b: -6}},
          {token: EmptySlots.slot12, cubeCoord: {r: 0, g: 6, b: -6}},

          {
            token: Tokens.entrance_left_b,
            cubeCoord: {r: -3, g: 3, b: 0},
          },
          {token: Tokens.exit_right_a, cubeCoord: {r: 2, g: -1, b: -1}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['B'],
    exits: ['A'],
    minor: 'STRENGTHEN all enemies.',
    major: 'STRENGTHEN all enemies permanently.',
  },
  Passage: {
    id: 'Passage',
    Tiles: [
      {
        Map: Tiles.K2b,
        staticRender: [
          {
            token: Tokens.boulder_2,
            cubeCoord: {r: 1.5, g: 0, b: -1.5},
          },
          {token: EmptySlots.slot1, cubeCoord: {r: -1, g: 2, b: -1}},
          {token: EmptySlots.slot2, cubeCoord: {r: -2, g: 2, b: 0}},
          {token: EmptySlots.slot3, cubeCoord: {r: -1, g: 3, b: -2}},
          {token: EmptySlots.slot4, cubeCoord: {r: 2, g: 4, b: -6}},
          {token: EmptySlots.slot5, cubeCoord: {r: 3, g: 4, b: -7}},
          {token: EmptySlots.slot6, cubeCoord: {r: 2, g: 5, b: -7}},
          {token: EmptySlots.slot7, cubeCoord: {r: 1, g: 2, b: -3}},
          {token: EmptySlots.slot8, cubeCoord: {r: 1, g: 1, b: -2}},
          {token: EmptySlots.slot9, cubeCoord: {r: 0, g: 2, b: -2}},
          {token: EmptySlots.slot10, cubeCoord: {r: 3, g: 0, b: -3}},
          {token: EmptySlots.slot11, cubeCoord: {r: 3, g: 1, b: -4}},
          {token: EmptySlots.slot12, cubeCoord: {r: 3, g: 2, b: -5}},
          {
            token: Tokens.entrance_left_a,
            cubeCoord: {r: -5, g: 5, b: 0},
          },
          {token: Tokens.exit_right_a, cubeCoord: {r: 3, g: 5, b: -8}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['A'],
    exits: ['A'],
    minor: 'Elite enemies gain INVISIBLE.',
    major: 'All enemies heal 1 hit point at the start of their turns.',
  },
  Road: {
    id: 'Road',
    Tiles: [
      {
        Map: Tiles.G1a,
        staticRender: [
          {
            token: Tokens.skew_log_2,
            cubeCoord: {r: 1.5, g: 1.5, b: -3},
          },
          {token: EmptySlots.slot1, cubeCoord: {r: 3, g: 1, b: -4}},
          {token: EmptySlots.slot2, cubeCoord: {r: 4, g: 0, b: -4}},
          {token: EmptySlots.slot3, cubeCoord: {r: 3, g: 0, b: -3}},
          {token: EmptySlots.slot4, cubeCoord: {r: 5, g: 1, b: -6}},
          {token: EmptySlots.slot5, cubeCoord: {r: 4, g: 1, b: -5}},
          {token: EmptySlots.slot6, cubeCoord: {r: 3, g: 2, b: -5}},
          {token: EmptySlots.slot7, cubeCoord: {r: 1, g: 0, b: -1}},
          {token: EmptySlots.slot8, cubeCoord: {r: 2, g: 0, b: -2}},
          {token: EmptySlots.slot9, cubeCoord: {r: 2, g: 2, b: -4}},
          {token: EmptySlots.slot10, cubeCoord: {r: 0, g: 2, b: -2}},
          {token: EmptySlots.slot11, cubeCoord: {r: 0, g: 1, b: -1}},
          {token: EmptySlots.slot12, cubeCoord: {r: -1, g: 2, b: -1}},
          {
            token: Tokens.entrance_right_b,
            cubeCoord: {r: 7, g: 1, b: -8},
          },
          {
            token: Tokens.entrance_right_a,
            cubeCoord: {r: 5, g: 3, b: -8},
          },
          {token: Tokens.exit_right_a, cubeCoord: {r: 5, g: -1, b: -4}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['A', 'B'],
    exits: ['A'],
    minor: 'Replace 1 normal enemy in the previous room.',
    major: 'Replace 2 normal enemies in the previous room.',
  },
  Sewer: {
    id: 'Sewer',
    Tiles: [
      {
        Map: Tiles.H1b,
        staticRender: [
          {token: EmptySlots.slot1, cubeCoord: {r: 2, g: 1, b: -3}},
          {token: EmptySlots.slot2, cubeCoord: {r: 0, g: 3, b: -3}},
          {token: EmptySlots.slot3, cubeCoord: {r: 1, g: 3, b: -4}},
          {token: EmptySlots.slot4, cubeCoord: {r: 2, g: 3, b: -5}},
          {token: EmptySlots.slot5, cubeCoord: {r: 4, g: 1, b: -5}},
          {token: EmptySlots.slot6, cubeCoord: {r: 5, g: 1, b: -6}},
          {token: EmptySlots.slot7, cubeCoord: {r: 5, g: 0, b: -5}},
          {token: EmptySlots.slot8, cubeCoord: {r: 1, g: 2, b: -3}},
          {token: EmptySlots.slot9, cubeCoord: {r: 2, g: 2, b: -4}},
          {token: EmptySlots.slot10, cubeCoord: {r: -1, g: 1, b: 0}},
          {token: EmptySlots.slot11, cubeCoord: {r: 0, g: 1, b: -1}},
          {token: EmptySlots.slot12, cubeCoord: {r: 0, g: 0, b: 0}},

          {
            token: Tokens.entrance_left_a,
            cubeCoord: {r: -1, g: 7, b: -6},
          },
          {token: Tokens.exit_right_a, cubeCoord: {r: 3, g: -1, b: -2}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['A'],
    exits: ['A'],
    minor: 'MUDDLE all characters.',
    major: 'MUDDLE all characters permanently.',
  },
  Trail: {
    id: 'Trail',
    Tiles: [
      {
        Map: Tiles.F1b,
        staticRender: [
          {
            token: Tokens.boulder_1,
            cubeCoord: {r: -1, g: 2, b: -1},
          },
          {
            token: Tokens.boulder_1,
            cubeCoord: {r: -1, g: 6, b: -5},
          },
          {token: EmptySlots.slot1, cubeCoord: {r: -2, g: 4, b: -2}},
          {token: EmptySlots.slot2, cubeCoord: {r: -1, g: 3, b: -2}},
          {token: EmptySlots.slot3, cubeCoord: {r: 0, g: 4, b: -4}},
          {token: EmptySlots.slot4, cubeCoord: {r: 0, g: 3, b: -3}},
          {token: EmptySlots.slot5, cubeCoord: {r: -3, g: 6, b: -3}},
          {token: EmptySlots.slot6, cubeCoord: {r: -2, g: 6, b: -4}},
          {token: EmptySlots.slot7, cubeCoord: {r: -1, g: 4, b: -3}},
          {token: EmptySlots.slot8, cubeCoord: {r: 1, g: 2, b: -3}},
          {token: EmptySlots.slot9, cubeCoord: {r: 0, g: 2, b: -2}},
          {token: EmptySlots.slot10, cubeCoord: {r: 0, g: 0, b: 0}},
          {token: EmptySlots.slot11, cubeCoord: {r: -1, g: 5, b: -4}},
          {token: EmptySlots.slot12, cubeCoord: {r: 2, g: 0, b: -2}},

          {
            token: Tokens.entrance_left_a,
            cubeCoord: {r: -3, g: 9, b: -6},
          },
          {token: Tokens.exit_left_b, cubeCoord: {r: -1, g: 1, b: 0}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['A'],
    exits: ['B'],
    minor: 'All characters spend all spendable items.',
    major:
      'All enemies add +1 MOVE to all their moves and +1 RANGE to all of their attacks.',
  },
  Tunnel: {
    id: 'Tunnel',
    Tiles: [
      {
        Map: Tiles.J1b,
        staticRender: [
          {
            token: Tokens.boulder_1,
            cubeCoord: {r: 5, g: 2, b: -7},
          },
          {
            token: Tokens.boulder_1,
            cubeCoord: {r: 3, g: 5, b: -8},
          },
          {
            token: Tokens.skew_boulder_2,
            cubeCoord: {r: 1, g: 1.5, b: -2.5},
          },
          {
            token: Tokens.boulder_3,
            cubeCoord: {r: 3.75, g: 0.5, b: -4.25},
          },
          {token: EmptySlots.slot1, cubeCoord: {r: 3, g: 2, b: -5}},
          {token: EmptySlots.slot2, cubeCoord: {r: 4, g: 4, b: -8}},
          {token: EmptySlots.slot3, cubeCoord: {r: 5, g: 3, b: -8}},
          {token: EmptySlots.slot4, cubeCoord: {r: 0, g: 0, b: 0}},
          {token: EmptySlots.slot5, cubeCoord: {r: 3, g: 3, b: -6}},
          {token: EmptySlots.slot6, cubeCoord: {r: 2, g: 0, b: -2}},
          {token: EmptySlots.slot7, cubeCoord: {r: 4, g: 3, b: -7}},
          {token: EmptySlots.slot8, cubeCoord: {r: 3, g: 0, b: -3}},
          {token: EmptySlots.slot9, cubeCoord: {r: 2, g: 2, b: -4}},
          {token: EmptySlots.slot10, cubeCoord: {r: 0, g: 1, b: -1}},
          {token: EmptySlots.slot11, cubeCoord: {r: 5, g: 1, b: -6}},
          {token: EmptySlots.slot12, cubeCoord: {r: 0, g: 2, b: -2}},
          {
            token: Tokens.entrance_left_b,
            cubeCoord: {r: 4, g: 6, b: -10},
          },
          {token: Tokens.exit_left_b, cubeCoord: {r: -1, g: 1, b: 0}},
          {token: Tokens.exit_left_a, cubeCoord: {r: 2, g: -1, b: -1}},
        ],
        offset: {x: 0, y: 0},
      },
    ],
    entries: ['B'],
    exits: ['B', 'A'],
    minor: 'CURSE all characters.',
    major: 'CURSE all characters three times.',
  },
}
