import {tokenPath} from '../config'
const fileFormat = '.png'
const drawCoords = {x: 0, y: 0}
export const Tokens = {
  altar: {
    id: 'altar',
    location: `${tokenPath}altar_vertical${fileFormat}`,
    aspectRatio: 4.1,
    drawCoords,
    itemType: 'token',
  },
  stone_pillar: {
    id: 'stone_pillar',
    location: `${tokenPath}stone_pillar${fileFormat}`,
    aspectRatio: 4.6,
    drawCoords,
    itemType: 'token',
  },
  entrance_left: {
    id: 'entrance_left',
    location: `${tokenPath}entrance_left${fileFormat}`,
    aspectRatio: 5,
    drawCoords,
    itemType: 'token',
  },
  entrance_right: {
    id: 'entrance_right',
    location: `${tokenPath}entrance_right${fileFormat}`,
    aspectRatio: 5,
    drawCoords,
    itemType: 'token',
  },
  exit_right: {
    id: 'exit_right',
    location: `${tokenPath}exit_right${fileFormat}`,
    aspectRatio: 5,
    drawCoords,
    itemType: 'token',
  },
  exit_left: {
    id: 'exit_left',
    location: `${tokenPath}exit_left${fileFormat}`,
    aspectRatio: 5,
    drawCoords,
    itemType: 'token',
  },
  coin: {
    id: 'coin',
    location: `${tokenPath}Coin${fileFormat}`,
    aspectRatio: 4.2,
    drawCoords,
    itemType: 'token',
  },
  treasure: {
    id: 'treasure',
    location: `${tokenPath}Treasure${fileFormat}`,
    aspectRatio: 4.2,
    drawCoords,
    itemType: 'token',
  },
  bear_trap: {
    id: 'bear_trap',
    location: `${tokenPath}Bear-Trap${fileFormat}`,
    aspectRatio: 4.0,
    drawCoords,
    itemType: 'token',
  },
  empty: {
    id: 'empty',
    location: `${tokenPath}empty${fileFormat}`,
    aspectRatio: 4,
    drawCoords,
    itemType: 'token',
  },
  boulder_1: {
    id: 'boulder_1',
    location: `${tokenPath}Boulder_1${fileFormat}`,
    aspectRatio: 4,
    drawCoords,
    itemType: 'token',
  },
  skew_boulder_2: {
    id: 'skew_boulder_2',
    location: `${tokenPath}skew_boulder_2${fileFormat}`,
    aspectRatio: 4.2,
    drawCoords,
    itemType: 'token',
  },
  boulder_2: {
    id: 'boulder_2',
    location: `${tokenPath}Boulder_2${fileFormat}`,
    aspectRatio: 4.2,
    drawCoords,
    itemType: 'token',
  },
  boulder_3: {
    id: 'boulder_3',
    location: `${tokenPath}Boulder_3${fileFormat}`,
    aspectRatio: 4.3,
    drawCoords,
    itemType: 'token',
  },
  corridor_1_s: {
    id: 'corridor_1_s',
    location: `${tokenPath}Corridor_1_S${fileFormat}`,
    aspectRatio: 4.3,
    drawCoords,
    itemType: 'token',
  },
  corridor_2_s: {
    id: 'corridor_2_s',
    location: `${tokenPath}Corridor_2_S${fileFormat}`,
    aspectRatio: 4.3,
    drawCoords,
    itemType: 'token',
  },
  corridor_1_w: {
    id: 'corridor_1_w',
    location: `${tokenPath}Corridor_1_W${fileFormat}`,
    aspectRatio: 4.6,
    drawCoords,
    itemType: 'token',
  },
  corridor_2_w: {
    id: 'corridor_2_w',
    location: `${tokenPath}Corridor_2_W${fileFormat}`,
    aspectRatio: 4.2,
    drawCoords,
    itemType: 'token',
  },
  corridor_1_ns: {
    id: 'corridor_1_ns',
    location: `${tokenPath}Corridor_1_NS${fileFormat}`,
    aspectRatio: 4.6,
    drawCoords,
    itemType: 'token',
  },
  corridor_1_e: {
    id: 'corridor_1_e',
    location: `${tokenPath}Corridor_1_E${fileFormat}`,
    aspectRatio: 4.6,
    drawCoords,
    itemType: 'token',
  },
  shelf_2: {
    id: 'shelf_2',
    location: `${tokenPath}Shelf_2${fileFormat}`,
    aspectRatio: 4.1,
    drawCoords,
    itemType: 'token',
  },
  table_2: {
    id: 'table_2',
    location: `${tokenPath}Table_2${fileFormat}`,
    aspectRatio: 3.9,
    drawCoords,
    itemType: 'token',
  },
  crate: {
    id: 'crate',
    location: `${tokenPath}Crate${fileFormat}`,
    aspectRatio: 4.6,
    drawCoords,
    itemType: 'token',
  },
  barrel: {
    id: 'barrel',
    location: `${tokenPath}Barrel${fileFormat}`,
    aspectRatio: 4.6,
    drawCoords,
    itemType: 'token',
  },
  cabinet: {
    id: 'cabinet',
    location: `${tokenPath}Cabinet${fileFormat}`,
    aspectRatio: 4.6,
    drawCoords,
    itemType: 'token',
  },
  rock_column: {
    id: 'rock_column',
    location: `${tokenPath}rock_column${fileFormat}`,
    aspectRatio: 4.6,
    drawCoords,
    itemType: 'token',
  },
  totem: {
    id: 'totem',
    location: `${tokenPath}Totem${fileFormat}`,
    aspectRatio: 4.8,
    drawCoords,
    itemType: 'token',
  },
  stalagmites: {
    id: 'stalagmites',
    location: `${tokenPath}Stalagmites${fileFormat}`,
    aspectRatio: 4.8,
    drawCoords,
    itemType: 'token',
  },
  nest: {
    id: 'nest',
    location: `${tokenPath}Nest${fileFormat}`,
    aspectRatio: 4,
    drawCoords,
    itemType: 'token',
  },
  skew_log_2: {
    id: 'skew_log_2',
    location: `${tokenPath}skew_log_2${fileFormat}`,
    aspectRatio: 4.3,
    drawCoords,
    itemType: 'token',
  },
  log_2: {
    id: 'log_2',
    location: `${tokenPath}Log_2${fileFormat}`,
    aspectRatio: 4.3,
    drawCoords,
    itemType: 'token',
  },
  bookcase_2: {
    id: 'bookcase_2',
    location: `${tokenPath}Bookcase_2${fileFormat}`,
    aspectRatio: 4.3,
    drawCoords,
    itemType: 'token',
  },
  skew_bookcase_2: {
    id: 'skew_bookcase_2',
    location: `${tokenPath}skew_bookcase_2${fileFormat}`,
    aspectRatio: 4.3,
    drawCoords,
    itemType: 'token',
  },
  thorns: {
    id: 'thorns',
    location: `${tokenPath}Thorns${fileFormat}`,
    aspectRatio: 4.3,
    drawCoords,
    itemType: 'token',
  },
  rubble: {
    id: 'rubble',
    location: `${tokenPath}Rubble${fileFormat}`,
    aspectRatio: 4.3,
    drawCoords,
    itemType: 'token',
  },
  spike_trap: {
    id: 'spike_trap',
    location: `${tokenPath}Spike-Trap${fileFormat}`,
    aspectRatio: 4.1,
    drawCoords,
    itemType: 'token',
  },
  water: {
    id: 'water',
    location: `${tokenPath}Water${fileFormat}`,
    aspectRatio: 4.7,
    drawCoords,
    itemType: 'token',
  },
  poison_trap: {
    id: 'poison_trap',
    location: `${tokenPath}Poison-Gas-Trap${fileFormat}`,
    aspectRatio: 4.1,
    drawCoords,
    itemType: 'token',
  },
  hot_coals: {
    id: 'hot_coals',
    location: `${tokenPath}Hot-Coals${fileFormat}`,
    aspectRatio: 4.1,
    drawCoords,
    itemType: 'token',
  },
}
